<div>
    <a href='javascript:void(0);' onClick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo get_the_permalink(); ?>', '_blank', 'width=600,height=600,scrollbars=yes,status=yes,resizable=yes,screenx=0,screeny=0');" class="ac white rd2 mb10 f16 dip" style="background: #3b5998;padding: 10px 0px; margin: 0px 5px 0px auto;"><i class="fa fa-facebook fa-lg pa10 shareicon"></i></a>

    <a href='javascript:void(0);' onClick="window.open('https://twitter.com/intent/tweet?original_referer=<?php echo get_the_permalink(); ?>&amp;text=<?php the_title(); ?>&amp;tw_p=tweetbutton&amp;url=<?php echo get_the_permalink(); ?>&amp;via=tribunnews', '_blank', 'width=600,height=600,scrollbars=yes,status=yes,resizable=yes,screenx=0,screeny=0');" class="ac white rd2 mb10 f16 dip" style="background: #4099ff;padding: 10px 0px; margin: 10px auto; margin-right:5px;"><i class="fa fa-twitter fa-lg pa10 shareicon"></i></a>

    <a href='javascript:void(0);' onClick="window.open('https://plus.google.com/share?url=<?php echo get_the_permalink(); ?>', '_blank', 'width=600,height=600,scrollbars=yes,status=yes,resizable=yes,screenx=0,screeny=0');" class="ac white rd2 mb10 f16 dip" style="background: #d34836;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-google-plus fa-lg pa10 shareicon"></i></a>

    <span href='#' onclick="shareother()" class="ac white rd2 mb10 f16 dip" style="cursor: pointer; color: #fff; background: #b2b2b2;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-share-alt pa10 shareicon"></i></span>
    <div id="shareother" class="shareother">
        <ul>
            <li class="ptb5" style="margin-top: 1px"><a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo get_the_permalink(); ?>&amp;t=<?php the_title(); ?>" title="Facebook" target="_blank" class="ac white rd2 mb10 f16 dip" style="background: #3b5998;padding: 10px 0px; margin: 10px auto;"><i class="fa fa-facebook fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="https://twitter.com/intent/tweet?original_referer=<?php echo get_the_permalink(); ?>&amp;text=<?php the_title(); ?>&amp;url=<?php echo get_the_permalink(); ?>&amp;via=tribunnews" title="Twitter" target="_blank" class="ac white rd2 mb10 f16 dip" style="background: #4099ff;padding: 10px 0px; margin: 10px auto; margin-right:5px;"><i class="fa fa-twitter fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="https://plus.google.com/share?url=<?php echo get_the_permalink(); ?>" title="Google Plus" target="_blank" class="ac white rd2 mb10 f16 dip" style="background: #d34836;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-google-plus fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="http://www.pinterest.com/pin/create/button/?url=<?php echo get_the_permalink(); ?>&amp;media=<?php echo tux_get_thumbnail_url(); ?>&amp;description=<?php the_title(); ?>" title="Pinterest" target="_blank"class="ac white rd2 mb10 f16 dip" style="background: #c8232c;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-pinterest-p fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="http://digg.com/submit?url=<?php echo get_the_permalink(); ?>&amp;title=<?php the_title(); ?>" title="Digg" target="_blank" class="ac rd2 mb10 f16 dip" style="background: #f0f0f0; padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-digg fa-lg pa10 shareicon" style="color: #000;"></i></a></li>
            <li class="ptb5"><a href="http://del.icio.us/save?jump=yes&amp;url=<?php echo get_the_permalink(); ?>&amp;title=<?php the_title(); ?>&amp;notes=<?php the_title(); ?>.&amp;via=tribunnews.com" title="Delicious" target="_blank" class="ac rd2 mb10 f16 dip" style="background: #0076e8;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-delicious fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="http://reddit.com/submit?url=<?php echo get_the_permalink(); ?>&amp;title=<?php the_title(); ?>" title="reddit" target="_blank" class="ac rd2 mb10 f16 dip" style="background: #FF4301;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-reddit-alien fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="http://www.stumbleupon.com/submit?url=<?php echo get_the_permalink(); ?>&amp;title=<?php the_title(); ?>" title="StumbleUpon"  target="_blank" class="ac rd2 mb10 f16 dip" style="background: #f74425;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-stumbleupon fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo get_the_permalink(); ?>&amp;title=<?php the_title(); ?>&amp;summary=<?php the_title(); ?>.&amp;source=<?php echo get_bloginfo('url');?>"  title="LinkenIn" target="_blank" class="ac rd2 mb10 f16 dip" style="background: #0e76a8;padding: 10px 0px; margin: 10px auto;margin-right:5px;"><i class="fa fa-linkedin fa-lg pa10 shareicon"></i></a></li>
            <li class="ptb5"><a href="http://web.whatsapp.com/send?text=<?php echo get_the_permalink();?>" rel="nofollow noopener" title="WhatsApp" target="_blank" class="ac white rd2 mb10 f16 dip" style="background: #25D366;padding: 10px 0; margin: 10px auto; margin-right:5px;"><i class="fa fa-whatsapp fa-lg pa10 shareicon"></i></a></li>
        </ul>
    </div>
</div>
